/*
 * The GNU GPL License 
 * Copyright (c) 2015-2016 IT Students of 5th year 
 * at the University of Maria Curie-Sklodowska in Lublin 
 */
package pl.medisoft.ui.admin.system;

import java.util.List;
import javax.swing.table.AbstractTableModel;
import pl.medisoft.application.message.Messages;
import pl.medisoft.domain.user.User;
import pl.medisoft.infrastructure.adminsys.model.UserTableModel;
import pl.medisoft.infrastructure.user.UserDao;
import pl.medisoft.infrastructure.user.UserDaoJpa;

/**
 *
 * @author Rafal
 */
public class AccountModifyiPane extends javax.swing.JPanel {

    private UserDao userDao = new UserDaoJpa();
    private List<User> users;
    private Messages messages;

    /**
     * Creates new form AccountModyfiPane
     */
    public AccountModifyiPane(Messages messages) {
        this.messages = messages;
        this.getData();
        initComponents();
        this.setDataToComponents();
    }

    private void getData() {
        this.users = this.userDao.findAll();

    }

    private AbstractTableModel getTableModel() {
        return new UserTableModel(this.users);
    }
    
    private void setDataToComponents(){
        this.jTable2.setModel(this.getTableModel());
    }

    private void refreshData() {

    }

    private void saveData() {

    }

    /*private void customize(){
        this.nameLabel.setText(this.messages.get("app.user.name"));
        this.surnameLabel.setText(this.messages.get("app.user.surname"));
        this.emailLabel.setText(this.messages.get("app.user.email"));
        this.countryLabel.setText(this.messages.get("app.user.country"));
        this.cityLabel.setText(this.messages.get("app.user.city"));
        this.postalCodeLabel.setText(this.messages.get("app.user.postalCode"));
        this.streetLabel.setText(this.messages.get("app.user.street"));
        this.houseNumberLabel.setText(this.messages.get("app.user.houseNumber"));
        this.userNameLabel.setText(this.messages.get("app.user.userName"));
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
